/**
 * THE CANONICAL STRING, CHECKED AGAINST THE WORKER THAT WILL VERIFY IT.
 *
 * A signature is either byte-identical to what the far side rebuilds or it is worthless, and the far
 * side is in another repository. So the vectors here are not copied out of `docs/infinite/API.md`;
 * they are GENERATED by importing moltworker's own `refs.ts` and `signed-request.ts` by path and
 * asking them what they would have built. A path import across repos is acceptable in a test (see
 * CLAUDE.md, "The sibling repo"), and a checkout that is not there skips with a sentence rather than
 * failing — CI is Linux and has one repo.
 *
 * The five things this pins are the five that have a refusal behind them: upper-case METHOD, PATH
 * carrying the query, seconds not milliseconds, the empty string's hash for a bodyless call, and the
 * nonce as the fifth line. Plus the claim, which is a different string again and the one most likely
 * to be got wrong, because it looks like it should be a signed request and is not.
 */
import { existsSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  APP_HEADER,
  EMPTY_BODY_HASH,
  NONCE_HEADER,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  bodyHashForBytes,
  canonicalString,
  claimMessage,
  newNonce,
  sha256Hex,
  signedHeaders,
  signedPath,
} from "../src/registry/signed.js";
import { b64u, signWithLinkKey, type LinkIdentity } from "../src/registry/link-key.js";

const DIR = "/Users/brunosilva/Documents/GitHub/moltworker/worker/src/infinite";
const HAVE_SIBLING = existsSync(`${DIR}/refs.ts`) && existsSync(`${DIR}/signed-request.ts`);

type WorkerRefs = {
  canonicalString(m: string, p: string, t: string, h: string, n: string): string;
  sha256Hex(text: string): Promise<string>;
  signedPath(url: string): string;
  verifyLinkSignature(linkPub: string, sig: string, message: string): Promise<boolean>;
  isLinkPub(value: unknown): boolean;
};
type WorkerSigned = {
  canonicalForRequest(method: string, url: string, timestamp: string, body: string, nonce: string): Promise<string>;
};

async function worker(): Promise<{ refs: WorkerRefs; signed: WorkerSigned }> {
  return {
    refs: (await import(/* @vite-ignore */ `${DIR}/refs.ts`)) as WorkerRefs,
    signed: (await import(/* @vite-ignore */ `${DIR}/signed-request.ts`)) as WorkerSigned,
  };
}

/** A link key without touching IndexedDB — `signWithLinkKey` takes the identity as an argument. */
async function key(): Promise<LinkIdentity> {
  const pair = (await crypto.subtle.generateKey({ name: "Ed25519" }, false, ["sign", "verify"])) as CryptoKeyPair;
  const raw = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey));
  return { publicKey: raw, publicKeyB64u: b64u(raw), privateKey: pair.privateKey };
}

const skip = (what: string) => {
  console.warn(`moltworker is not checked out beside 00Local — ${what} is skipped.`);
};

describe("the five lines", () => {
  it("is METHOD, PATH, TIMESTAMP, sha256(body), NONCE", () => {
    expect(canonicalString("get", "/infinite/apps/iaa_x/inbox?since=1", "1757000000", "abc", "n0nce12345")).toBe(
      "GET\n/infinite/apps/iaa_x/inbox?since=1\n1757000000\nabc\nn0nce12345",
    );
  });

  it("keeps the query in PATH, so a cursor cannot be lifted", () => {
    expect(signedPath("https://x.example/infinite/apps/a/inbox?since=0&includeDrained=1")).toBe(
      "/infinite/apps/a/inbox?since=0&includeDrained=1",
    );
    expect(signedPath("https://x.example/infinite/apps/a")).toBe("/infinite/apps/a");
  });

  it("hashes the EMPTY STRING for a bodyless call, not an empty field", async () => {
    expect(await sha256Hex("")).toBe(EMPTY_BODY_HASH);
  });

  it("mints a nonce inside the worker's 8–64 band", () => {
    for (let i = 0; i < 20; i++) {
      const n = newNonce();
      expect(n.length).toBeGreaterThanOrEqual(8);
      expect(n.length).toBeLessThanOrEqual(64);
      expect(n).toMatch(/^[A-Za-z0-9_-]+$/);
    }
    expect(newNonce()).not.toBe(newNonce());
  });

  it("builds the four headers and no fifth", async () => {
    const id = await key();
    const headers = await signedHeaders({
      appId: "iaa_abc",
      method: "POST",
      url: "https://x.example/infinite/apps/iaa_abc/link",
      body: '{"stAppId":null,"overblastCid":null}',
      sign: (m) => signWithLinkKey(m, id),
      now: () => 1_757_000_000_000,
      nonce: "nonce-one-two",
    });
    expect(Object.keys(headers).sort()).toEqual([APP_HEADER, NONCE_HEADER, SIGNATURE_HEADER, TIMESTAMP_HEADER].sort());
    // SECONDS. Milliseconds here look like a clock fifty thousand years fast and answer stale_signature.
    expect(headers[TIMESTAMP_HEADER]).toBe("1757000000");
  });
});

describe.skipIf(!HAVE_SIBLING)("against the worker that verifies it", () => {
  it("builds the same canonical string the worker rebuilds", async () => {
    if (!HAVE_SIBLING) return skip("the canonical-string vectors");
    const { refs, signed } = await worker();
    const cases: { method: string; url: string; body: string; nonce: string; ts: string }[] = [
      { method: "GET", url: "https://api.example/infinite/apps/iaa_a/origins", body: "", nonce: "aaaaaaaa", ts: "1757000000" },
      {
        method: "GET",
        url: "https://api.example/infinite/apps/iaa_a/inbox?since=2026-09-10T00%3A00%3A00.000Z&includeDrained=1",
        body: "",
        nonce: "bbbbbbbbbb",
        ts: "1757000001",
      },
      { method: "POST", url: "https://api.example/infinite/apps/iaa_a/origins", body: '{"origin":"https://shop.example","status":"allowed"}', nonce: "cccccccc", ts: "1757000002" },
      { method: "DELETE", url: "https://api.example/infinite/apps/iaa_a/push-subscriptions", body: '{"endpoint":"https://push.example/x"}', nonce: "dddddddd", ts: "1757000003" },
      { method: "PUT", url: "https://api.example/infinite/apps/iaa_a/public-bundle", body: '{"version":1,"files":[]}', nonce: "eeeeeeee", ts: "1757000004" },
    ];
    for (const c of cases) {
      const ours = canonicalString(c.method, signedPath(c.url), c.ts, await sha256Hex(c.body), c.nonce);
      const theirs = await signed.canonicalForRequest(c.method, c.url, c.ts, c.body, c.nonce);
      expect(ours).toBe(theirs);
      expect(refs.signedPath(c.url)).toBe(signedPath(c.url));
    }
  });

  it("hashes a BINARY body the way the worker does — decoded as UTF-8 first", async () => {
    if (!HAVE_SIBLING) return skip("the binary-body vector");
    const { refs } = await worker();
    const bytes = new TextEncoder().encode('{"version":1,"files":[{"path":"PERSONA.md","text":"héllo ✧"}]}');
    // routes.ts: `new TextDecoder('utf-8', { fatal: false }).decode(bytes)` before `sha256Hex`.
    expect(await bodyHashForBytes(bytes)).toBe(await refs.sha256Hex(new TextDecoder("utf-8", { fatal: false }).decode(bytes)));
  });

  it("produces a request signature the worker verifies", async () => {
    if (!HAVE_SIBLING) return skip("the signature check");
    const { refs, signed } = await worker();
    const id = await key();
    const url = "https://api.example/infinite/apps/iaa_a/inbox?since=0";
    const headers = await signedHeaders({
      appId: "iaa_a",
      method: "GET",
      url,
      sign: (m) => signWithLinkKey(m, id),
      now: () => 1_757_000_000_000,
    });
    const message = await signed.canonicalForRequest("GET", url, headers[TIMESTAMP_HEADER], "", headers[NONCE_HEADER]);
    expect(await refs.verifyLinkSignature(id.publicKeyB64u, headers[SIGNATURE_HEADER], message)).toBe(true);
    // And a signature over a DIFFERENT query is not liftable onto this one.
    const lifted = await signed.canonicalForRequest("GET", `${url}00`, headers[TIMESTAMP_HEADER], "", headers[NONCE_HEADER]);
    expect(await refs.verifyLinkSignature(id.publicKeyB64u, headers[SIGNATURE_HEADER], lifted)).toBe(false);
  });

  it("signs the claim as appId‖origin‖nonce, plain concatenation", async () => {
    if (!HAVE_SIBLING) return skip("the claim vector");
    const { refs } = await worker();
    const id = await key();
    const appId = "iaa_7fk2";
    const origin = "https://shop.example";
    const nonce = "Zm9vYmFyYmF6";
    const sig = await signWithLinkKey(claimMessage(appId, origin, nonce), id);
    // `registry.ts::claimApp` verifies over exactly this string and no other.
    expect(await refs.verifyLinkSignature(id.publicKeyB64u, sig, `${appId}${origin}${nonce}`)).toBe(true);
    // Separators are the obvious wrong guess, and they fail.
    expect(await refs.verifyLinkSignature(id.publicKeyB64u, sig, `${appId}\n${origin}\n${nonce}`)).toBe(false);
    // So is signing THIS window's origin instead of the site's registration origin.
    const wrong = await signWithLinkKey(claimMessage(appId, "https://infinite.example", nonce), id);
    expect(await refs.verifyLinkSignature(id.publicKeyB64u, wrong, `${appId}${origin}${nonce}`)).toBe(false);
  });

  it("exports a link public key the worker calls well-formed", async () => {
    if (!HAVE_SIBLING) return skip("the link-pub check");
    const { refs } = await worker();
    const id = await key();
    expect(refs.isLinkPub(id.publicKeyB64u)).toBe(true);
    expect(id.publicKeyB64u).not.toContain("=");
    expect(id.publicKey.length).toBe(32);
  });
});
